sudo: required
before_install:
  - ./launch-test-nginx.sh daemon $NGINX_VERSION
services:
  - docker

script: bash run-tests.sh

env:
  matrix:
    - NGINX_VERSION=1.13.3-1
    - NGINX_VERSION=1.12.0-1
    - NGINX_VERSION=1.11.9-0
    - NGINX_VERSION=1.11.5-0
    - NGINX_VERSION=1.10.1-3
    - NGINX_VERSION=1.10.1-0
